- name : Configure Docker on EC2 Instances
  hosts : all
  become: yes
  connection : ssh
  tasks : 
  - name: updating apt
    command : "rm -rf /var/lib/dpkg/lock*"
    
  - name: updating apt
    command : "apt-get update"
    
  - name : Install Docker
    command : apt-get install -y docker.io

  - name : Start Docker Service
    command : systemctl start docker

  - name: Deploy Docker Container
    command: docker run -itd -p 8083:8081 oswinjoy/healthcare:latest
